paths:
  data: "/workspaces/US_Data_scrape_morgenroutine/source"
  raw: "/workspaces/US_Data_scrape_morgenroutine/source/data2"
  processed: "C:/Users/domin/Desktop/Morgenroutine_stuff/processed"

loader:
  stooq_url: "https://stooq.com/db/h/"
  symbols:
    - nasdaq
    - nyse
    - amex

compute:
  nhnl_lookback: 252
  penny_filter: 1.0
